import { useShallow } from 'zustand/react/shallow'
import { useNotebookStore } from '../store/notebookStore'

export function useCells() {
    return useNotebookStore(useShallow((s: any) => ({
        hasCellMinSize: s.hasCellMinSize,
        hasCellMaxSize: s.hasCellMaxSize,
        hasCellHeight: s.hasCellHeight,
        isSqlCellWithEditor: s.isSqlCellWithEditor,
        bodyDisplayShouldShowSkeleton: s.bodyDisplayShouldShowSkeleton,
        bodyDisplayShouldShowContent: s.bodyDisplayShouldShowContent,
        getCellHeightVars: s.getCellHeightVars,
        getCellSizeOuterClass: s.getCellSizeOuterClass,
        getCellWrapperStyle: s.getCellWrapperStyle,
        getCellSizeInnerClass: s.getCellSizeInnerClass,
        createNewCell: s.createNewCell,
        addGroup: s.addGroup,
        addCellToGroup: s.addCellToGroup,
        openAddCellToGroupModal: s.openAddCellToGroupModal,
        openInsertGroupModal: s.openInsertGroupModal,
        insertGroupAt: s.insertGroupAt,
        openInsertCellModal: s.openInsertCellModal,
        insertCellAt: s.insertCellAt,
        deleteGroup: s.deleteGroup,
        moveGroup: s.moveGroup,
        deleteCellAt: s.deleteCellAt,
        moveCellInGroup: s.moveCellInGroup,
        ensureCellName: s.ensureCellName,
        ensureAllCellsHaveNames: s.ensureAllCellsHaveNames,
        openCellConfig: s.openCellConfig,
        getCommonParamsForType: s.getCommonParamsForType,
        getCommonParamsExcludingName: s.getCommonParamsExcludingName,
        getCommonParamDef: s.getCommonParamDef,
        getSpecificParamsForType: s.getSpecificParamsForType,
        isSpecificParamVisible: s.isSpecificParamVisible,
        getQueryLabelForType: s.getQueryLabelForType,
        getQueryCountForType: s.getQueryCountForType,
        getCellValueByPath: s.getCellValueByPath,
        setCellValueByPath: s.setCellValueByPath,
        onCellTypeChange: s.onCellTypeChange,
        generateUniqueCellName: s.generateUniqueCellName,
        isCellNameUsed: s.isCellNameUsed,
        generateUniqueSourceName: s.generateUniqueSourceName,
        validateCellName: s.validateCellName,
        validateSingleSourceName: s.validateSingleSourceName,
        // state
        cellConfigModal: s.cellConfigModal,
        addCellToGroupModal: s.addCellToGroupModal,
        insertGroupModal: s.insertGroupModal,
        insertCellModal: s.insertCellModal,
    })))
}
